baseURL = "http://example.org/"
languageCode = "en-us"
title = "Randy Ridenour — Presentations"
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"

[author]
name = "Randy Ridenour"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "simple"




