baseURL = "http://example.org/"
languageCode = "en-us"
title = "Randy Ridenour — Presentations"

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "white"